packages/css/example/index.css, packages/css/src/components/datatable.scss, packages/modules/pgr/src/components/MobileInbox.js, packages/modules/pgr/src/components/inbox/ComplaintCard.js, packages/modules/pgr/src/hooks/useComplaintDetails.js, packages/modules/pgr/src/pages/citizen/ComplaintDetails.js, packages/modules/pgr/src/pages/citizen/CreateComplaint/Address.js, packages/modules/pgr/src/pages/citizen/CreateComplaint/TimeLine.js, packages/modules/pgr/src/pages/employee/ComplaintDetails.js, packages/react-components/src/atoms/ImageUploadHandler.js, packages/react-components/src/atoms/Toast.js, packages/react-components/src/atoms/UploadImages.js, packages/react-components/src/molecules/DetailsCard.js
Complaint Summary and image upload bugs fixed
=> Pgr hotfixes

packages/libraries/src/hooks/store.js, packages/libraries/src/services/Complaint.js, packages/modules/core/src/Module.js
Fixed react query unexpected behaviour and completed assign workflow
=> rerender fixed and assign flow errors fixed

packages/react-components/src/atoms/SubmitBar.js
Submit bar submitting even after disabled bug fixed
=> fixed submit button working even after disabled

packages/css/example/index.css, packages/css/src/components/card.scss, packages/modules/pgr/src/components/Complaint.js
Fixed css issue in complaint details employee and fixed rejected complaints appearing as open
=> Pgr complaint fixes

example/src/index.js, example/src/userInfo/qa-gro-nawanshahr.json, example/src/userInfo/qa-gro.json, packages/modules/pgr/src/constants/Routes.js, packages/modules/pgr/src/pages/citizen/index.js, packages/modules/pgr/src/pages/employee/index.js, packages/react-components/src/atoms/UploadFile.js
These bugs have small changes in routing params and slicing long string, bug/LIN-108 and bug/LIN-110 are not bugs so doesn't need any fix
=> fixed bug/LIN-107 bug/LIN-109

packages/css/src/components/selectdropdown.scss, packages/css/src/components/topbar.scss, packages/css/src/pages/employee/index.scss, packages/modules/core/src/components/App.js, packages/react-components/src/atoms/Dropdown.js
[Fix]
- Topbar of citizen And Employee 
- SideBar of Citizen in desktop View
=> topbar and sidebar fixes

packages/libraries/src/hooks/fsm/useApplicationActions.js, packages/libraries/src/hooks/fsm/useSearchAll.js, packages/libraries/src/hooks/index.js, packages/libraries/src/services/molecules/FSM/ApplicationUpdateActions.js, packages/modules/fsm/src/pages/Response.js, packages/modules/fsm/src/pages/citizen/ApplicationDetails.js, packages/modules/fsm/src/pages/citizen/MyApplications/index.js, packages/modules/fsm/src/pages/employee/EditApplication/index.js, packages/modules/fsm/src/pages/employee/NewApplication/index.js
1. Flows tested working 
2. DSO Screends modals completed
3. Refactoring and code cleanup done
=> Feature/dso UI updates

packages/css/src/index.scss, packages/modules/fsm/src/pages/employee/EditApplication/index.js, packages/react-components/src/atoms/CardText.js, packages/react-components/src/atoms/Dropdown.js, packages/react-components/src/atoms/TextArea.js, packages/react-components/src/atoms/TextInput.js, packages/react-components/src/atoms/svgindex.js, packages/react-components/src/hoc/FormComposer.js, packages/react-components/src/molecules/PitDimension.js
=> add field modification by FSM_CREATOR_EMP role

packages/css/src/pages/employee/index.scss, packages/modules/core/package.json, packages/modules/core/src/components/App.js, packages/react-components/src/atoms/Hamburger.js
https://user-images.githubusercontent.com/75667085/107361867-06028d00-6afe-11eb-9f81-20b0161f7e9e.mp4
https://user-images.githubusercontent.com/75667085/107361887-0dc23180-6afe-11eb-8b39-39a2bbbfdf4c.mp4
=> add hamburger to desktop citizen and center citizen cards

example/package.json, example/src/index.js, package.json, packages/css/src/pages/employee/index.scss, packages/modules/common/src/payments/index.js, packages/modules/core/src/components/Home.js, packages/modules/pt/package.json, packages/modules/pt/src/Module.js, packages/modules/pt/src/pages/citizen/MyApplications/index.js, packages/modules/pt/src/pages/citizen/MyApplications/my-application.js, packages/modules/pt/src/pages/citizen/MyBills/index.js, packages/modules/pt/src/pages/citizen/MyBills/my-bill.js, packages/modules/pt/src/pages/citizen/MyReceipts/index.js, packages/modules/pt/src/pages/citizen/MyReceipts/my-receipt.js, packages/modules/pt/src/pages/citizen/SearchProperty/config.js, packages/modules/pt/src/pages/citizen/SearchProperty/index.js, packages/modules/pt/src/pages/citizen/SearchProperty/searchProperty.js, packages/modules/pt/src/pages/citizen/SearchResults/config.js, packages/modules/pt/src/pages/citizen/SearchResults/index.js, packages/modules/pt/src/pages/citizen/SearchResults/searchResults.js, packages/modules/pt/src/pages/citizen/bill-details/bill-summary.js, packages/modules/pt/src/pages/citizen/bill-details/index.js, packages/modules/pt/src/pages/citizen/index.js, packages/modules/pt/src/pages/employee/index.js, packages/react-components/src/atoms/AppContainer.js, packages/react-components/src/atoms/KeyNote.js, packages/react-components/src/atoms/TextInput.js, packages/react-components/src/hoc/FormComposer.js, packages/react-components/src/hoc/ResponseComposer.js, packages/react-components/src/index.js
- Search Property
- Search Results
- My Applications
- Receipts
- My Bill And Bill Details
=> Pt changes

packages/modules/fsm/src/getPDFData.js
This PR does 1 thing:
* It update localization key from CS_APPLICATION_DETAILS_BUILDING to CS_APPLICATION_DETAILS_DOOR_NO
=> update localization key

packages/modules/fsm/src/components/inbox/FSMLink.js
This PR does two things:
1. Remove Reports link on fsm employee inbox
2. Update employee inbox dashboard redirect url
After:
https://user-images.githubusercontent.com/75667085/107760092-3ee57080-6d4f-11eb-93ce-695458870585.mp4
=> update employee inbox links redirect

packages/modules/fsm/src/pages/citizen/ApplicationDetails.js
This PR does 1 thing:
* It will hide the timeline heading when timeline have no data to show
=> hide timeline heading when timeline is empty

packages/modules/fsm/src/pages/citizen/FileComplaint/SelectAddress.js
https://user-images.githubusercontent.com/75667085/107756692-97663f00-6d4a-11eb-99ef-3bd5ae96f989.mp4
=> Citizen UI :: City and Locality field should not be user entry

packages/libraries/src/services/molecules/FSM/Search.js, packages/modules/fsm/src/pages/employee/EditApplication/index.js, packages/modules/fsm/src/pages/employee/NewApplication/index.js
=> Fixed application details page and modify application form

packages/modules/core/src/components/Home.js
=> Remove application audit link from home

packages/modules/fsm/src/pages/citizen/FileComplaint/SelectGeolocation.js, packages/react-components/src/molecules/LocationSearchCard.js
This PR fixes 3 issues in citizen geolocation screen:
1. skip link is not working
2. localization keys not coming
3. next should be disabled till no location is selected on map
=> fix geolocation ui issues

packages/modules/fsm/src/pages/employee/ApplicationDetails/index.js, packages/modules/fsm/src/pages/employee/EditApplication/index.js, packages/modules/fsm/src/pages/employee/NewApplication/index.js
https://user-images.githubusercontent.com/75667085/108033898-b4588600-705a-11eb-9c58-a9b9dfd5311c.mp4
https://user-images.githubusercontent.com/75667085/108033778-84a97e00-705a-11eb-8090-12e272ada91c.mp4
=> fix application details state is not updating after take any action

packages/modules/core/src/components/Home.js
=> hide fsm home card for fstp user

packages/modules/fsm/src/pages/citizen/FileComplaint/SelectTankSize.js
https://www.loom.com/share/5b5d7de08b054ddfb7a741636bbfe82d
=> fix pit tank size can submiit even if one of the field in entered

packages/css/src/components/card.scss
=> fix PGR new application from employee page has css alignment issue

packages/modules/fsm/src/pages/citizen/FileComplaint/SelectAddress.js, packages/modules/fsm/src/pages/citizen/FileComplaint/SelectPitType.js, packages/modules/pgr/src/pages/citizen/Create/Steps/SelectAddress.js
https://www.loom.com/share/0df790a5eb4645108f7c27a3c09b48b6
https://www.loom.com/share/5ad8f0b1143f477eaeabf0c855fe2e9a
=> feature: Add radio button for dropdown menu have less then 5 items

packages/modules/fsm/src/pages/employee/ApplicationDetails/index.js, packages/modules/fsm/src/pages/employee/FstpOperatorDetails.js, packages/modules/pgr/src/pages/citizen/ComplaintDetails.js, packages/modules/pgr/src/pages/employee/ComplaintDetails.js
=> fix Emp UI :: Should display NA for the fields which are left empty

packages/modules/core/src/components/App.js, packages/react-components/src/atoms/NavBar.js
https://www.loom.com/share/61654c18f6c64f299866b1e30ab24ddd
=> mobile screen scrolls below the screen

packages/css/src/pages/employee/index.scss, packages/modules/common/src/payments/citizen/response/index.js, packages/modules/common/src/payments/employee/response/index.js, packages/modules/common/src/payments/index.js, packages/modules/fsm/src/Module.js, packages/modules/pgr/src/Module.js
=> fix citizen home css

packages/modules/core/src/pages/citizen/Login/config.js, packages/modules/fsm/src/components/MobileInbox.js, packages/modules/fsm/src/components/inbox/ApplicationCard.js
Fixed mobile inbox for fsm employee
=> Add submit button label in login page

packages/css/src/components/card.scss, packages/css/src/pages/employee/inbox.scss, packages/css/src/pages/employee/index.scss, packages/modules/fsm/src/Module.js
=> fix mobile view employee home page css

packages/react-components/src/atoms/Dropdown.js
https://digit-discuss.atlassian.net/browse/FSM-162
=> fix City and Locality field should not be user entry

packages/modules/common/src/payments/employee/payment-collect/index.js, packages/modules/fsm/src/components/DesktopInbox.js, packages/modules/fsm/src/pages/Response.js, packages/modules/fsm/src/pages/citizen/Rating/SelectRating.js, packages/modules/fsm/src/pages/employee/FstpOperatorDetails.js
Fixed raitng issue
Fixed payment page issue
=> bug - 22, 24, 39

packages/modules/core/src/components/App.js, packages/react-components/src/atoms/Dropdown.js
=> remove unnecessary logout scrollbar

packages/css/src/components/datatable.scss, packages/react-components/src/atoms/StatusTable.js
=> fix diameter and depth alignment issue

packages/libraries/src/services/elements/WorkFlow.js, packages/libraries/src/services/molecules/FSM/Search.js, packages/modules/fsm/src/pages/employee/ApplicationDetails/index.js
=> Fixed application timeline

packages/modules/fsm/src/pages/citizen/Rating/SelectRating.js
=> change rating and spillage text order

packages/libraries/src/utils/pdf.js, packages/modules/fsm/src/getPDFData.js
=> fix localization and alignment issues

packages/css/src/pages/employee/index.scss, packages/libraries/src/hooks/fsm/useDsoSearch.js, packages/modules/fsm/src/components/CustomTimePicker.js, packages/modules/fsm/src/pages/citizen/ApplicationDetails.js, packages/modules/fsm/src/pages/employee/FstpOperatorDetails.js
Add dso details in citizen
Fixed fstp time picker
=> Add dso details in citizen

packages/modules/fsm/src/components/inbox/ApplicationLinks.js
This PR does two things
1. hide dashboard links for everyone
2. show new application for creator role only
=> showing new desuldging application for creator role only

packages/modules/fsm/src/components/inbox/Filter.js, packages/modules/fsm/src/components/inbox/SortBy.js, packages/modules/fsm/src/components/inbox/search.js, packages/modules/pgr/src/components/inbox/Filter.js, packages/modules/pgr/src/components/inbox/search.js, packages/react-components/src/atoms/svgindex.js, packages/react-components/src/index.js
=> add material ui close svg

packages/css/src/components/datatable.scss
=> fix slum name alignment issue

packages/modules/fsm/src/components/DesktopInbox.js, packages/modules/fsm/src/components/inbox/search.js, packages/modules/fsm/src/pages/employee/Inbox.js
This PR does 2 things
1. fix fstp inbox alignment
2. remove unused code
=> fix fstp inbox alignment issue

packages/modules/fsm/src/pages/citizen/NewApplication/CheckPage.js
=> add change button for slum name in Citizen check page

packages/css/src/components/card.scss, packages/modules/fsm/src/pages/employee/ApplicationDetails/Modal/index.js, packages/modules/fsm/src/pages/employee/ApplicationDetails/config/CompleteApplication.js
"Vehicle Registration No and Vehicle Capacity font is too bold - under the Assign Vehicle pop up window 
Similarly all the other popup font bold type needs to be changed and only the Title of pop up should be bold."
"DSO login - Take Action - Complete Request calendar :: Able to select previous date on completing request
Expected : Previous dates from application creation date should be disabled "
=> Bug/task 220-and-194

packages/modules/fsm/src/pages/citizen/ApplicationDetails.js
Citizen-My Applications-View :: If Geolocation not selected then in view page should display only "" NA "". should not display the map.
While creating Application from Citizen do not select the property location from map go to next page with skip and continue, submit the application and check the same application in view page."
=> citizen application details - either display map or NA

packages/libraries/src/services/molecules/FSM/DsoDetails.js, packages/libraries/src/services/molecules/FSM/Search.js, packages/modules/fsm/package.json, packages/modules/fsm/src/components/ApplicationTimeline.js, packages/modules/fsm/src/components/CustomTimePicker.js, packages/react-components/src/atoms/OTPInput.js, yarn.lock
=> Add rate button in timeline

packages/css/src/index.scss, packages/modules/common/src/payments/citizen/bills/pt/my-bills.js
PT :: Not able to find the property? Click Here is not available in My Bills screen
https://digit-discuss.atlassian.net/browse/LIN-113
=> Fix PT :: Not able to find the property?

packages/css/src/index.scss, packages/modules/common/src/payments/citizen/bills/pt/bill-details.js, packages/modules/pt/src/pages/citizen/SearchResults/searchResults.js, packages/react-components/src/atoms/Card.js
PT :: Date is not displayed for Due Date and Payment Amount card is not static in My Bills screen
https://digit-discuss.atlassian.net/browse/LIN-114
=> Fix PT :: Payment Amount card is not static in My Bills screen

packages/modules/fsm/src/getPDFData.js, packages/modules/fsm/src/pages/citizen/Rating/SelectRating.js
https://digit-discuss.atlassian.net/browse/FSM-300
=> fix pdf amountPerTrip and total amount NA after rate

packages/modules/fsm/src/getPDFData.js
https://digit-discuss.atlassian.net/browse/FSM-310
=> Fix amountPerTrip & totalAmount displaying as NA after application update

packages/css/src/index.scss, packages/modules/common/src/payments/citizen/bills/routes/my-bills/my-bills.js
https://digit-discuss.atlassian.net/browse/LIN-113?focusedCommentId=32325
=> Fix “Not able to find the property? Click Here” is not static.

packages/modules/pt/src/pages/citizen/SearchProperty/config.js, packages/modules/pt/src/pages/citizen/SearchProperty/searchProperty.js, packages/react-components/src/hoc/FormComposer.js
https://digit-discuss.atlassian.net/browse/LIN-120
=> add mobile number description

packages/libraries/src/hooks/pt/usePropertyAPI.js, packages/modules/pt/src/Module.js, packages/modules/pt/src/pageComponents/SelectOwnerDetails.js, packages/modules/pt/src/pageComponents/SelectProofIdentity.js, packages/modules/pt/src/pages/citizen/Create/CheckPage.js, packages/modules/pt/src/pages/citizen/Create/PTAcknowledgement.js, packages/modules/pt/src/pages/citizen/Create/index.js, packages/modules/pt/src/pages/citizen/MyApplications/application-details.js, packages/modules/pt/src/pages/citizen/MyApplications/index.js, packages/modules/pt/src/pages/citizen/MyApplications/my-application.js, packages/modules/pt/src/pages/citizen/MyProperties/index.js, packages/modules/pt/src/pages/citizen/MyProperties/my-properties.js, packages/modules/pt/src/pages/citizen/MyProperties/propertyInformation.js
=> RAIN-2299 : PT Create API integrated with Acknowledgement screen

packages/modules/common/src/payments/citizen/bills/routes/bill-details/bill-details.js
https://digit-discuss.atlassian.net/browse/LIN-118
=> add validation to custom amount

packages/modules/common/src/payments/citizen/bills/routes/bill-details/bill-details.js, packages/modules/common/src/payments/citizen/response/index.js
https://digit-discuss.atlassian.net/browse/LIN-115?focusedCommentId=32472
~ symbol is displayed in Billing Period (- should be used) FY 2018~2019
=> ~ symbol is displayed in Billing Period (- should be used)

packages/modules/common/src/payments/citizen/keynotesConfig.js
https://digit-discuss.atlassian.net/browse/LIN-114
=> Proper Due Date should be displayed in My Bills screen

packages/modules/fsm/src/components/inbox/StatusCount.js, packages/modules/fsm/src/pages/citizen/Rating/RateView.js
Fixed status count with locality
=> Fixed rating localization bug

packages/libraries/src/utils/pdf.js
=> fix pdf email is too long so partially displayed

packages/modules/pt/src/config/Create/config.js, packages/modules/pt/src/pageComponents/IsResidential.js, packages/modules/pt/src/pageComponents/PropertyUsageType.js, packages/modules/pt/src/pages/citizen/Create/CheckPage.js, packages/modules/pt/src/pages/citizen/MyApplications/index.js, packages/modules/pt/src/pages/citizen/MyProperties/index.js
these are the fix for :
add new property button
data being displayed when clicking back button (isResdential Page)
back button working for the isResdential yes and no flow.
=> Pt create flow fixes

packages/modules/pt/src/pages/citizen/index.js, packages/react-components/src/atoms/BackButton.js
=> Pt demo fixes

packages/modules/pt/src/pageComponents/SelectOwnerDetails.js
RAIn-2415 (PT Citizen :: Relationship field name is not displayed while creating property application)
=> RAIn-2415 (PT Citizen :: Relationship field name is not displayed while creating property application)

packages/modules/fsm/src/pageComponents/SelectAddress.js
sending city data to onSelect whenever selectedCity update instead of dropdown selectCity function
=> add default city to SelectAddress onSelect

packages/libraries/src/hooks/pt/usePropertyMDMS.js, packages/libraries/src/services/elements/MDMS.js, packages/modules/pt/src/config/Create/config.js, packages/modules/pt/src/pageComponents/RentalDetails.js
Rental Details - 7.5% should not be hardcoded
=> Rental Details - 7.5% should not be hardcoded

packages/css/src/index.scss, packages/modules/common/src/payments/citizen/bills/routes/my-bills/my-bills.js, packages/modules/pt/src/pages/citizen/SearchProperty/searchProperty.js, packages/modules/pt/src/pages/citizen/SearchResults/searchResults.js
This PR fix these issues:
1. Search Results label is not proper - Not Fixed
2. Want to add a new Property? Click Here is not available on the Search Result screen - Not Fixed
https://digit-discuss.atlassian.net/browse/LIN-127
=> fix pt issues

packages/modules/pt/src/pages/citizen/PTApplicationDetails.js
Added dowloand option for application summary
=> RAIN-2423 :PT Added dowloand option for application summary

packages/css/src/components/uploadcomponents.scss, packages/modules/pt/src/pageComponents/Proof.js, packages/modules/pt/src/pageComponents/SelectProofIdentity.js, packages/modules/pt/src/pageComponents/SelectSpecialProofIdentity.js, packages/modules/pt/src/pages/citizen/index.js
RAIN-2418 (PT Citizen :: Intermittent Issue :: 'Choose file' button is navigating to next screen while creating Property application)
=> RAIN-2418 (PT Citizen :: Intermittent Issue :: 'Choose file' button is navigating to next screen while creating Property application)

packages/modules/pt/src/pages/citizen/SearchResults/searchResults.js
https://digit-discuss.atlassian.net/browse/LIN-127?focusedCommentId=32679
=> showing click here to next line

packages/modules/pt/src/pageComponents/Area.js, packages/modules/pt/src/pageComponents/GroundFloorDetails.js, packages/modules/pt/src/pageComponents/RentalDetails.js, packages/modules/pt/src/pageComponents/SelectInistitutionOwnerDetails.js, packages/modules/pt/src/pageComponents/SelectOwnerDetails.js, packages/modules/pt/src/pageComponents/UnOccupiedArea.js
PT Citizen :: Input field validations related issues
=> PT Citizen :: Input field validations related issues

packages/modules/pt/src/pages/citizen/MyProperties/index.js, packages/modules/pt/src/pages/citizen/PTMyApplications/index.js, packages/modules/pt/src/pages/citizen/index.js, packages/modules/pt/src/utils/index.js
RAIN-2416 (PT Citizen :: The back button should be static on the screen)
=> RAIN-2416 (PT Citizen :: The back button should be static on the screen)

packages/modules/pt/src/pages/citizen/MyProperties/propertyInformation.js, packages/modules/pt/src/pages/citizen/PTApplicationDetails.js
RAIN-2423 (PT Citizen :: Download option is not available on the Application details screen)
=> RAIN-2423 (PT Citizen :: Download option is not available on the Application details screen)

packages/modules/pt/src/Module.js, packages/modules/pt/src/pages/citizen/MyProperties/TransferDetails.js, packages/modules/pt/src/pages/citizen/MyProperties/propertyInformation.js, packages/modules/pt/src/pages/citizen/MyProperties/propertyOwnerHistory.js, packages/modules/pt/src/pages/citizen/index.js, packages/modules/pt/src/utils/index.js
RAIN-2425 (PT Citizen :: Digit Citizen inbox is loaded when clicked on the Owner History option from the Property Information screen)
=> RAIN-2425 (PT Citizen :: Digit Citizen inbox is loaded when clicked on the Owner History option from the Property Information screen)

packages/modules/pt/src/pageComponents/SelectInistitutionOwnerDetails.js, packages/modules/pt/src/utils/index.js
RAIN-2335 (owner-details integration)
=> RAIN-2335 (owner-details integration)

packages/modules/pt/src/pageComponents/Proof.js, packages/modules/pt/src/pageComponents/SelectProofIdentity.js, packages/modules/pt/src/pageComponents/SelectSpecialProofIdentity.js, packages/modules/pt/src/pages/citizen/Create/CheckPage.js, packages/modules/pt/src/utils/index.js
RAIN-2473 (integration and summary page changes)
=> RAIN-2473 (integration and summary page changes)

packages/modules/pt/src/pageComponents/Proof.js, packages/modules/pt/src/pageComponents/SelectProofIdentity.js, packages/modules/pt/src/pageComponents/SelectSpecialProofIdentity.js, packages/react-components/src/atoms/ButtonSelector.js, packages/react-components/src/atoms/UploadFile.js
RAIN-2418 (PT Citizen ::  Intermittent Issue :: 'Choose file' button is navigating to next screen while creating Property application)
=> RAIN-2418 (PT Citizen ::  Intermittent Issue :: 'Choose file' button is navigating to next screen while creating Property application)

packages/modules/pt/src/pageComponents/SelectOwnerAddress.js, packages/react-components/src/atoms/CheckBox.js
RAIN-2427 (PT Citizen :: Alignment related issues in application create flow)
=> RAIN-2427 (PT Citizen :: Alignment related issues in application create flow)

packages/modules/pt/src/pageComponents/PTWFApplicationTimeline.js, packages/modules/pt/src/pages/citizen/PTApplicationDetails.js
RAIN-2412 (PT Citizen :: Action buttons should be static on the screen)
=> RAIN-2412 (PT Citizen :: Action buttons should be static on the screen)

packages/modules/pt/src/pageComponents/PTWFApplicationTimeline.js, packages/modules/pt/src/pageComponents/SelectInistitutionOwnerDetails.js, packages/modules/pt/src/pageComponents/SelectOwnerDetails.js, packages/modules/pt/src/pageComponents/SelectOwnerShipDetails.js, packages/modules/pt/src/pageComponents/SelectProofIdentity.js, packages/modules/pt/src/pageComponents/SelectSpecialOwnerCategoryType.js, packages/modules/pt/src/pageComponents/SelectSpecialProofIdentity.js, packages/modules/pt/src/pages/citizen/Create/CheckPage.js, packages/modules/pt/src/pages/citizen/EditProperty/index.js, packages/modules/pt/src/pages/citizen/index.js, packages/modules/pt/src/utils/index.js, packages/react-components/src/atoms/RadioButtons.js
RAIN-2336 , RAIN-2489 (UI- Property Edit Property Application (Send Back to Citizen) flow)
=> RAIN-2336 , RAIN-2489 (UI- Property Edit Property Application (Send Back to Citizen) flow)

packages/modules/pt/src/pageComponents/GroundFloorDetails.js, packages/modules/pt/src/pages/citizen/EditProperty/index.js, packages/modules/pt/src/utils/index.js
send back to citizen
for flat or part of the building
for independent property
=> Pt edit property work

packages/libraries/src/hooks/pt/usePropertyAPI.js, packages/modules/pt/src/pageComponents/Proof.js, packages/modules/pt/src/pages/citizen/Create/PTAcknowledgement.js, packages/modules/pt/src/pages/citizen/EditProperty/index.js, packages/modules/pt/src/utils/index.js
RAIN-2336 (UI- Property Edit Property Application (Send Back to Citizen) flow)
=> RAIN-2336 (UI- Property Edit Property Application (Send Back to Citizen) flow)

packages/modules/core/src/components/Home.js, packages/modules/fsm/src/pageComponents/SelectStreet.js
add validation in street and door field
=> disable quick pay

packages/modules/pt/src/pageComponents/PTSelectAddress.js, packages/modules/pt/src/pageComponents/PTSelectGeolocation.js, packages/modules/pt/src/pageComponents/PTSelectPincode.js, packages/modules/pt/src/pages/citizen/Create/CheckPage.js, packages/modules/pt/src/pages/citizen/EditProperty/index.js
RAIN-2336-2 (UI- Property Edit Property Application (Send Back to Citizen) flow)
=> RAIN-2336-2 (UI- Property Edit Property Application (Send Back to Citizen) flow)

packages/modules/pt/src/pageComponents/PTSelectAddress.js, packages/modules/pt/src/pageComponents/PTSelectPincode.js, packages/modules/pt/src/pageComponents/SelectInistitutionOwnerDetails.js, packages/modules/pt/src/pageComponents/SelectOwnerAddress.js, packages/modules/pt/src/pageComponents/SelectOwnerDetails.js, packages/modules/pt/src/pageComponents/SelectOwnerShipDetails.js, packages/modules/pt/src/pageComponents/SelectSpecialOwnerCategoryType.js, packages/modules/pt/src/pages/citizen/Create/CheckPage.js, packages/modules/pt/src/pages/citizen/EditProperty/index.js, packages/modules/pt/src/pages/citizen/MyProperties/propertyInformation.js, packages/modules/pt/src/utils/index.js, packages/react-components/src/atoms/RadioButtons.js, packages/react-components/src/molecules/FormStep.js
RAIN-2467 (Create and edit Property new UI: Dev testing and Gaps closure)
=> RAIN-2467 (Create and edit Property new UI: Dev testing and Gaps closure)

packages/modules/pt/src/pages/citizen/EditProperty/index.js, packages/modules/pt/src/utils/index.js
and addition of usage category for vacant (send back to citizen)
=> fixed the create api issue for vacant property 

packages/modules/pt/src/pageComponents/Area.js, packages/modules/pt/src/pageComponents/ProvideSubUsageType.js, packages/modules/pt/src/pageComponents/ProvideSubUsageTypeOfRentedArea.js, packages/modules/pt/src/pageComponents/RentalDetails.js, packages/modules/pt/src/pageComponents/SelectProofIdentity.js, packages/modules/pt/src/pageComponents/UnOccupiedArea.js
Validation added for unit area
checkpage bug fixed
repeat option in usage category bug fixed
Localization key updated for annual rent
=> error msg for unit area & multi owner, checkpage bug fixed

packages/modules/pt/src/pageComponents/SelectOwnerAddress.js
RAIN-2565 (PT Citizen :: Not able to proceed after uploading document for Special Owner Category Proof)
=> RAIN-2565 (PT Citizen :: Not able to proceed after uploading document for Special Owner Category Proof)

packages/modules/pt/src/pageComponents/Proof.js, packages/modules/pt/src/pageComponents/SelectProofIdentity.js, packages/modules/pt/src/pageComponents/SelectSpecialProofIdentity.js
RAIN-2564 PT Citizen :: Select Document type drop-down should be added in the document Upload screen
=> RAIN-2564 PT Citizen :: Select Document type drop-down should be added in the document Upload screen

packages/modules/pt/src/pageComponents/PropertyTax.js, packages/modules/pt/src/pages/citizen/EditProperty/index.js
RAIN-2416 PT Citizen :: The back button should be static on the screen
=> RAIN-2416 PT Citizen :: The back button should be static on the screen

packages/modules/pt/src/pageComponents/PropertyTax.js
RAIN-2416 aPT Citizen :: The back button should be static on the screen
=> RAIN-2416 aPT Citizen :: The back button should be static on the screen

packages/libraries/src/utils/pdf.js
=> fix maximum characters bug for value

packages/modules/pt/src/pageComponents/Proof.js, packages/modules/pt/src/pageComponents/SelectProofIdentity.js, packages/modules/pt/src/pageComponents/SelectSpecialProofIdentity.js, packages/modules/pt/src/utils/index.js
RAIN-2564 (PT Citizen :: Select Document type drop-down should be added in the document Upload screen)
=> RAIN-2564 (PT Citizen :: Select Document type drop-down should be added in the document Upload screen)

packages/modules/pt/src/pageComponents/Proof.js, packages/modules/pt/src/pageComponents/SelectProofIdentity.js, packages/modules/pt/src/pageComponents/SelectSpecialProofIdentity.js, packages/react-components/src/atoms/Dropdown.js
RAIN-2573 PT Citizen :: Select Document label is not displayed while uploading documents
=> RAIN-2573 PT Citizen :: Select Document label is not displayed while uploading documents

packages/modules/pt/src/pages/citizen/EditProperty/index.js, packages/modules/pt/src/utils/index.js
RAIN-2581 (updated documentTypes and fixed create and update API errors)
=> RAIN-2581 (updated documentTypes and fixed create and update API errors)

packages/modules/pt/src/pageComponents/SelectOwnerDetails.js
RAIN-2590 PT Citizen APK :: Number keypad is opened while entering Name and Guardian details for Single and Multiple owners details
=> RAIN-2590 PT Citizen APK :: Number keypad is opened while entering Name and Guardian details for Single and Multiple owners details

packages/libraries/src/services/atoms/urls.js, packages/libraries/src/services/elements/PT.js, packages/modules/pt/src/pages/citizen/MyProperties/propertyInformation.js
…roeprty status based fetch bill
=> RAIN-2588 : Property Info screen added assessment search and property status based fetch bill

packages/modules/pt/src/pageComponents/PTSelectAddress.js, packages/modules/pt/src/pages/citizen/EditProperty/index.js, packages/react-components/src/molecules/RadioOrSelect.js
RAIN-2549 PT Citizen :: Selected values are not prepopulated while editing the application
=> RAIN-2549 PT Citizen :: Selected values are not prepopulated while editing the application

packages/modules/pt/src/pageComponents/Proof.js, packages/modules/pt/src/pageComponents/SelectInistitutionOwnerDetails.js, packages/modules/pt/src/pageComponents/SelectProofIdentity.js, packages/modules/pt/src/pageComponents/SelectSpecialProofIdentity.js, packages/react-components/src/atoms/UploadFile.js
RAIN-2627 document issues fixed
=> RAIN-2627 document issues fixed

packages/modules/mCollect/src/components/DesktopInbox.js, packages/modules/mCollect/src/components/MCollectCard.js, packages/modules/mCollect/src/components/inbox/Filter.js, packages/modules/mCollect/src/components/inbox/InboxLink.js, packages/modules/mCollect/src/components/inbox/NewInboxFilter.js, packages/modules/mCollect/src/components/inbox/ServiceCategory.js, packages/modules/mCollect/src/components/inbox/ServiceCategoryCount.js, packages/modules/mCollect/src/components/inbox/Status.js, packages/modules/mCollect/src/components/inbox/StatusCount.js, packages/modules/mCollect/src/pages/employee/Inbox.js, packages/modules/mCollect/src/pages/employee/index.js
RAIN-2524 (search integration)
=> RAIN-2524 (search integration)

packages/css/src/components/charts.scss, packages/css/src/components/filters.scss, packages/modules/dss/src/Module.js, packages/modules/dss/src/components/CustomHorizontalBarChart.js, packages/modules/dss/src/components/CustomPieChart.js, packages/modules/dss/src/components/CustomTable.js, packages/modules/dss/src/components/DateRange.js, packages/modules/dss/src/components/Filters.js, packages/modules/dss/src/components/Layout.js, packages/modules/dss/src/components/MetricChart.js, packages/modules/dss/src/components/Switch.js, packages/modules/dss/src/pages/index.js, packages/react-components/src/atoms/Header.js
Reverts egovernments/digit-ui-internals#772
=> Revert "Fix table chart"

packages/modules/mCollect/src/components/DesktopInbox.js, packages/modules/mCollect/src/components/inbox/ServiceCategory.js, packages/modules/mCollect/src/pages/employee/Inbox.js, packages/modules/mCollect/src/utils/index.js
RAIN-2524-1 (integration of download receipts are done)
=> RAIN-2524-1 (integration of download receipts are done)

packages/modules/mCollect/src/components/DesktopInbox.js, packages/modules/mCollect/src/utils/index.js
RAIN-2524 updated localization keys
=> RAIN-2524 updated localization keys

packages/modules/mCollect/src/components/MobileInbox.js, packages/modules/mCollect/src/components/inbox/ApplicationCard.js, packages/modules/mCollect/src/components/inbox/ApplicationLinks.js, packages/modules/mCollect/src/components/inbox/InboxLink.js, packages/modules/mCollect/src/pages/employee/Inbox.js
RAIN-2524 mobile view support changes
=> RAIN-2524 mobile view support changes

packages/modules/mCollect/src/EmployeeChallan.js, packages/modules/mCollect/src/components/DesktopInbox.js, packages/modules/mCollect/src/utils/index.js
RAIN-2528 UI: mCollect Employee Challan Information screen static changes and integration with challan search api
=> RAIN-2528 UI: mCollect Employee Challan Information screen static changes and integration with challan search api

packages/libraries/src/services/atoms/Utils/Request.js, packages/libraries/src/services/atoms/urls.js, packages/libraries/src/services/elements/MCollect.js, packages/modules/mCollect/src/EmployeeChallan.js, packages/modules/mCollect/src/components/Modal/MCollectActionModal.js, packages/modules/mCollect/src/components/Modal/MCollectRejectApplication.js, packages/modules/mCollect/src/components/Modal/MCollectWFAcknowledgement.js, packages/modules/mCollect/src/components/Modal/index.js, packages/modules/mCollect/src/pages/employee/EmployeeChallanAcknowledgement.js, packages/modules/mCollect/src/pages/employee/index.js, packages/modules/mCollect/src/utils/index.js
RAIN-2529 UI: mCollect Employee Challan Information screen Actions config and integration with Download challan , Receipts
=> RAIN-2529 UI: mCollect Employee Challan Information screen Actions config and integration with Download challan , Receipts

packages/modules/mCollect/src/EmployeeChallan.js, packages/modules/mCollect/src/Module.js, packages/modules/mCollect/src/components/Modal/MCollectActionModal.js, packages/modules/mCollect/src/components/inbox/Filter.js, packages/modules/mCollect/src/components/inbox/NewInboxFilter.js, packages/modules/mCollect/src/components/inbox/ServiceCategory.js, packages/modules/mCollect/src/components/inbox/Status.js, packages/modules/mCollect/src/components/inbox/search.js, packages/modules/mCollect/src/pages/employee/EmployeeChallanAcknowledgement.js, packages/modules/mCollect/src/pages/employee/Inbox.js, packages/modules/mCollect/src/utils/index.js
RAIN-2523 updated localizatios and added localization service in mcollect module
=> RAIN-2523 updated localizatios and added localization service in mcollect module

packages/modules/mCollect/src/pages/employee/Utils/Category.js
Un necessary Data Populate issue Fixed
=> Rain 2527 fixes

packages/modules/mCollect/src/EmployeeChallan.js, packages/modules/mCollect/src/components/inbox/search.js, packages/modules/mCollect/src/pages/employee/Inbox.js
RAIN-2529 added more details in mcollect
=> RAIN-2529 added more details in mcollect

packages/modules/core/src/components/App.js
=> RAIN-2702 : Common Updated the footer image and added digit link for footer

packages/modules/mCollect/src/components/MCollectCard.js, packages/modules/mCollect/src/pages/employee/EmployeeChallanAcknowledgement.js, packages/modules/mCollect/src/pages/employee/Inbox.js, packages/modules/mCollect/src/pages/employee/index.js
RAIN-2523 localization keys added
=> RAIN-2523 localization keys added

packages/modules/mCollect/src/pages/employee/index.js
=> RAIN-2523 added styles

packages/libraries/src/utils/index.js, packages/modules/mCollect/src/components/MCollectCard.js
RAIN-2523 Give access for mcollect
=> RAIN-2523 Give access for mcollect

package.json
=> Hrms hot fixes

packages/modules/hrms/src/components/pageComponents/SelectEmailId.js, packages/modules/hrms/src/components/pageComponents/SelectEmployeeGender.js, packages/modules/hrms/src/components/pageComponents/assignment.js
- Edit mode disable of employee id
- resolved async call in assignments map
- gender menu fixes
=> HRMS bug fixes

packages/libraries/src/hooks/index.js, packages/libraries/src/hooks/tl/useTradeLicenseBillingslab.js, packages/libraries/src/services/atoms/urls.js, packages/libraries/src/services/elements/TL.js, packages/modules/fsm/src/pageComponents/SelectStreet.js, packages/modules/tl/src/Module.js, packages/modules/tl/src/components/TLCard.js, packages/modules/tl/src/config/config.js, packages/modules/tl/src/pageComponents/SelectOwnerShipDetails.js, packages/modules/tl/src/pageComponents/TLAccessoriesEmployee.js, packages/modules/tl/src/pageComponents/TLDocumentsEmployee.js, packages/modules/tl/src/pageComponents/TLOwnerDetailsEmployee.js, packages/modules/tl/src/pageComponents/TLSelectAddress.js, packages/modules/tl/src/pageComponents/TLSelectPincode.js, packages/modules/tl/src/pageComponents/TLTradeDetailsEmployee.js, packages/modules/tl/src/pageComponents/TLTradeUnitsEmployee.js, packages/modules/tl/src/pages/Response.js, packages/modules/tl/src/pages/employee/NewApplication/index.js, packages/modules/tl/src/pages/employee/index.js, packages/modules/tl/src/utils/index.js, packages/react-components/src/hoc/FormComposer.js
RAIN-2804 RAIN-2805,  UI/UX Employee Revamp: TL Create a New TL Application + Acknowledgement Screen
=> RAIN-2804 RAIN-2805,  UI/UX Employee Revamp: TL Create a New TL Application + Acknowledgement Screen

example/src/setupProxy.js, packages/modules/tl/src/pageComponents/TLAccessoriesEmployee.js, packages/modules/tl/src/pageComponents/TLTradeDetailsEmployee.js
RAIN-2805 added licese types from mdms
=> RAIN-2805 added licese types from mdms

packages/modules/tl/src/pageComponents/TLAccessoriesEmployee.js, packages/modules/tl/src/pageComponents/TLSelectAddress.js, packages/modules/tl/src/pageComponents/TLTradeDetailsEmployee.js, packages/modules/tl/src/utils/index.js
=> RAIN-2805 added validations

packages/libraries/src/hooks/index.js, packages/libraries/src/hooks/tl/useApplicationActions.js, packages/libraries/src/hooks/tl/useApplicationDetail.js, packages/libraries/src/services/molecules/TL/ApplicationUpdateActions.js, packages/libraries/src/services/molecules/TL/Search.js, packages/modules/templates/ApplicationDetails/components/ApplicationDetailsActionBar.js, packages/modules/templates/ApplicationDetails/components/ApplicationDetailsContent.js, packages/modules/templates/ApplicationDetails/components/PropertyDocuments.js, packages/modules/templates/ApplicationDetails/components/TLTradeAccessories.js, packages/modules/templates/ApplicationDetails/components/TLTradeUnits.js, packages/modules/tl/src/pages/employee/ApplicationDetails.js, packages/modules/tl/src/pages/employee/index.js
RAIN-2807 UI/UX Employee Revamp: TL Trade Details Static changes + API Integration
=> RAIN-2807 UI/UX Employee Revamp: TL Trade Details Static changes + API Integration

packages/modules/mCollect/src/components/DesktopInbox.js
RAIN-2938 mCollect :: Page alignment of inbox is not proper.
=> RAIN-2938 mCollect :: Page alignment of inbox is not proper.

packages/modules/hrms/src/components/inbox/DesktopInbox.js, packages/modules/hrms/src/components/pageComponents/assignment.js, packages/modules/hrms/src/components/pageComponents/jurisdiction.js, packages/modules/hrms/src/pages/EmployeeDetails.js, packages/react-components/src/atoms/MultiSelectDropdown.js, packages/react-components/src/atoms/Table.js, packages/react-components/src/hoc/FormComposer.js
Some common changes done in table component to not show the next arrow in case of row lenth ==1
and form composer in case of field is disabled , label is made disabled
=> RAIN-2941 : Receipts no result found on few cases issue is resolved

packages/modules/templates/ApplicationDetails/Modal/TLActionModal.js, packages/modules/templates/ApplicationDetails/Modal/index.js, packages/modules/templates/ApplicationDetails/config/TLApproverApplication.js, packages/modules/templates/ApplicationDetails/config/index.js, packages/modules/templates/ApplicationDetails/index.js, packages/modules/tl/src/pages/employee/ApplicationDetails.js
RAIN-2807 workflow integration changes
=> RAIN-2807 workflow integration changes

packages/libraries/src/services/molecules/TL/Search.js, packages/modules/templates/ApplicationDetails/components/ApplicationDetailsContent.js, packages/modules/templates/ApplicationDetails/components/PropertyOwners.js, packages/modules/templates/ApplicationDetails/components/TLTradeAccessories.js, packages/modules/templates/ApplicationDetails/components/TLTradeUnits.js, packages/modules/tl/src/pages/employee/ApplicationDetails.js
RAIN-2806 Trade applications details changes
=> RAIN-2806 Trade applications details changes

packages/libraries/src/hooks/mcollect/useMCollectMDMS.js, packages/libraries/src/services/elements/MDMS.js, packages/modules/mCollect/src/components/inbox/Status.js
RAIN-2958 mCollect :: Status Filters options are not listed in UI.
=> RAIN-2958 mCollect :: Status Filters options are not listed in UI.

packages/modules/tl/src/pageComponents/SelectOwnerShipDetails.js, packages/modules/tl/src/pageComponents/TLAccessoriesEmployee.js, packages/modules/tl/src/pageComponents/TLOwnerDetailsEmployee.js, packages/modules/tl/src/pageComponents/TLTradeDetailsEmployee.js, packages/modules/tl/src/pages/employee/NewApplication/index.js
RAIN-2806  TL Application Details changes
=> RAIN-2806  TL Application Details changes

packages/libraries/src/services/molecules/TL/Search.js, packages/modules/templates/ApplicationDetails/components/ApplicationDetailsToast.js, packages/modules/templates/ApplicationDetails/config/TLApproverApplication.js, packages/modules/tl/src/utils/getTLAcknowledgementData.js
=> RAIN-2747 added pdf changes

packages/modules/tl/src/pageComponents/TLAccessoriesEmployee.js, packages/modules/tl/src/pageComponents/TLTradeDetailsEmployee.js, packages/modules/tl/src/pageComponents/TLTradeUnitsEmployee.js, packages/modules/tl/src/utils/getTLAcknowledgementData.js
RAIN-2807 updated locations and validations
=> RAIN-2807 updated locations and validations

packages/libraries/src/utils/pdf.js, packages/modules/common/src/payments/employee/index.js, packages/modules/common/src/payments/employee/payment-collect/index.js, packages/modules/common/src/payments/employee/response/index.js, packages/modules/tl/src/components/SearchApplication.js, packages/modules/tl/src/pageComponents/TLTradeDetailsEmployee.js, packages/modules/tl/src/utils/getTLAcknowledgementData.js
RAIN-2807 license certification integration
=> RAIN-2807 license certification integration

packages/modules/tl/src/pageComponents/TLDocumentsEmployee.js
=> removed DocumetUID

packages/modules/tl/src/pageComponents/TLDocumentsEmployee.js
=> RAIN-2807 added validations

packages/modules/tl/src/Module.js, packages/modules/tl/src/config/config.js, packages/modules/tl/src/pageComponents/TLAccessoriesEmployee.js, packages/modules/tl/src/pageComponents/TLDocumentsEmployee.js, packages/modules/tl/src/pageComponents/TLInfoLabel.js, packages/modules/tl/src/pageComponents/TLOwnerDetailsEmployee.js, packages/modules/tl/src/pageComponents/TLSelectAddress.js, packages/modules/tl/src/pageComponents/TLTradeDetailsEmployee.js, packages/modules/tl/src/pageComponents/TLTradeUnitsEmployee.js, packages/modules/tl/src/pages/employee/ReNewApplication/index.js, packages/modules/tl/src/pages/employee/index.js
RAIN-2982 UI/UX Employee Revamp : TL Apply for direct and Edit renewal use case
=> RAIN-2982 UI/UX Employee Revamp : TL Apply for direct and Edit renewal use case

packages/libraries/src/services/molecules/TL/Search.js, packages/modules/fsm/src/pageComponents/SelectStreet.js, packages/modules/templates/ApplicationDetails/Modal/index.js, packages/modules/templates/ApplicationDetails/components/ApplicationDetailsToast.js, packages/modules/tl/src/pageComponents/SelectOwnerShipDetails.js, packages/modules/tl/src/pageComponents/TLAccessoriesEmployee.js, packages/modules/tl/src/pageComponents/TLDocumentsEmployee.js, packages/modules/tl/src/pageComponents/TLOwnerDetailsEmployee.js, packages/modules/tl/src/pageComponents/TLSelectAddress.js, packages/modules/tl/src/pageComponents/TLSelectPincode.js, packages/modules/tl/src/pageComponents/TLTradeDetailsEmployee.js, packages/modules/tl/src/pageComponents/TLTradeUnitsEmployee.js, packages/modules/tl/src/pages/Response.js, packages/modules/tl/src/pages/employee/ApplicationDetails.js, packages/modules/tl/src/pages/employee/ReNewApplication/index.js, packages/modules/tl/src/pages/employee/Search.js, packages/modules/tl/src/utils/index.js
Rain 2982 UI/UX Employee Revamp : TL Apply for direct and Edit renewal use case
=> Rain 2982 UI/UX Employee Revamp : TL Apply for direct and Edit renewal use case

packages/modules/tl/src/pageComponents/TLAccessoriesEmployee.js
added conditions for new application and renewal
=> added conditions for new application and renewal

packages/modules/tl/src/components/TLCard.js, packages/modules/tl/src/components/inbox/DesktopInbox.js, packages/modules/tl/src/pages/employee/ReNewApplication/index.js
RAIN-3059 TL :: 'Create New Employee' page is displayed on clicking options from Trade License box on Inbox Page
=> RAIN-3059 TL :: 'Create New Employee' page is displayed on clicking options from Trade License box on Inbox Page

packages/modules/templates/ApplicationDetails/components/ApplicationDetailsToast.js, packages/modules/tl/src/pages/employee/ApplicationDetails.js, packages/modules/tl/src/pages/employee/index.js
RAIN-2747 enable cancel and expire actions
=> RAIN-2747 enable cancel and expire actions

packages/modules/tl/src/pages/employee/ApplicationDetails.js
=> RAIN-2747: TL Validations added for the Application details of Direct renewal

packages/modules/tl/src/pages/employee/ApplicationDetails.js
RAIN-2747 Renewal of Trade License: Integration of workflow actions, print, download receipts and applications.
=> RAIN-2747 Renewal of Trade License: Integration of workflow actions, print, download receipts and applications.

packages/modules/tl/src/pageComponents/TLTradeDetailsEmployee.js, packages/modules/tl/src/pages/employee/ApplicationDetails.js, packages/modules/tl/src/pages/employee/NewApplication/index.js, packages/modules/tl/src/pages/employee/ReNewApplication/index.js
RAIN-2804 added sorting and removed consoles
=> RAIN-2804 added sorting and removed consoles

packages/modules/tl/src/pageComponents/TLOwnerDetailsEmployee.js
RAIN-2804 updated gender type options intigration
=> RAIN-2804 updated gender type options intigration

packages/modules/tl/src/pageComponents/SelectOwnerShipDetails.js, packages/modules/tl/src/pageComponents/TLAccessoriesEmployee.js, packages/modules/tl/src/pageComponents/TLOwnerDetailsEmployee.js, packages/modules/tl/src/pageComponents/TLTradeDetailsEmployee.js, packages/modules/tl/src/pageComponents/TLTradeUnitsEmployee.js, packages/react-components/src/atoms/Dropdown.js, packages/react-components/src/atoms/MobileNumber.js, packages/react-components/src/atoms/TextInput.js
=> RAIN-2804 TL CREATE Form validations changes as per review comments

packages/modules/tl/src/components/SearchLicense.js
RAIN-3095 TL :: Clicking on Trade license number is navigating to citizen digit-UI home page
=> RAIN-3095 TL :: Clicking on Trade license number is navigating to citizen digit-UI home page

packages/libraries/src/services/molecules/TL/Search.js
RAIN-3140 TL :: Locality is displayed in codes on Trade Details screen
=> RAIN-3140 TL :: Locality is displayed in codes on Trade Details screen

packages/modules/tl/src/components/SearchApplication.js, packages/modules/tl/src/components/SearchLicense.js, packages/modules/tl/src/components/inbox/DesktopInbox.js, packages/modules/tl/src/utils/index.js
RAIN-3119 TL :: Application Date is not displayed as per figma
=> RAIN-3119 TL :: Application Date is not displayed as per figma

packages/modules/tl/src/components/SearchApplication.js, packages/modules/tl/src/components/SearchLicense.js
RAIN-3114  TL :: Not able to search using Dates and trade License number on Search Application screen
=> RAIN-3114  TL :: Not able to search using Dates and trade License number on Search Application screen

packages/libraries/src/services/molecules/TL/Search.js, packages/modules/tl/src/components/SearchApplication.js, packages/modules/tl/src/components/SearchLicense.js
RAIN-3167, RAIN-3140, RAIN-3114 TL :: Details are not displayed properly on Trade Details screen
=> RAIN-3167, RAIN-3140, RAIN-3114 TL :: Details are not displayed properly on Trade Details screen

packages/modules/tl/src/pageComponents/TLWFApplicationTimeline.js
RAIN-3072 TL :: Application timeline is broken on application details page
=> RAIN-3072 TL :: Application timeline is broken on application details page

packages/modules/tl/src/components/TLCard.js
RAIN-3140 TL :: Locality is displayed in codes
=> RAIN-3140 TL :: Locality is displayed in codes

packages/modules/mCollect/src/components/inbox/search.js
RAIN-3091 added latest styles for mCollect inbox
=> RAIN-3091 added latest styles for mCollect inbox

packages/modules/tl/src/pageComponents/TLAccessoriesEmployee.js, packages/modules/tl/src/pageComponents/TLOwnerDetailsEmployee.js, packages/modules/tl/src/pageComponents/TLSelectAddress.js, packages/modules/tl/src/pageComponents/TLTradeUnitsEmployee.js
RAIN-3181 TL :: Employee :: Add Trade Unit and Add Accessories button is clickable from entire row
=> RAIN-3181 TL :: Employee :: Add Trade Unit and Add Accessories button is clickable from entire row

packages/modules/mCollect/src/components/inbox/InboxLink.js
RAIN-3183 mCollect :: mCollect Inbox :: Challan search screen in employee is not proper.
=> RAIN-3183 mCollect :: mCollect Inbox :: Challan search screen in employee is not proper.

packages/libraries/src/hooks/index.js, packages/libraries/src/hooks/mcollect/useMCollectCount.js, packages/libraries/src/services/atoms/urls.js, packages/libraries/src/services/elements/MCollect.js, packages/modules/mCollect/src/components/MCollectCard.js, packages/modules/mCollect/src/components/inbox/InboxLink.js, packages/react-components/src/atoms/EmployeeModuleCard.js
RAIN-3087 mCollect :: Total Challan Count is not shown on digit ui Homepage on mCollect Card.
=> RAIN-3087 mCollect :: Total Challan Count is not shown on digit ui Homepage on mCollect Card.

packages/modules/mCollect/src/components/MCollectCard.js, packages/modules/tl/src/components/SearchLicense.js
RAIN-3186 TL :: Employee :: Trade owner's Number field is not displayed on Renew Trade License Search screen
=> RAIN-3186 TL :: Employee :: Trade owner's Number field is not displayed on Renew Trade License Search screen

packages/modules/mCollect/src/components/DesktopInbox.js, packages/modules/mCollect/src/pages/employee/Inbox.js
RAIN-3087 mCollect :: NA is displayed in Inbox for 1-2 secs, Instead of Collect.
=> RAIN-3087 mCollect :: NA is displayed in Inbox for 1-2 secs, Instead of Collect.

packages/libraries/src/services/molecules/TL/Search.js, packages/modules/templates/ApplicationDetails/components/PropertyOwners.js
RAIN-3150 TL :: Employee :: Application details screen is not designed as per figma
=> RAIN-3150 TL :: Employee :: Application details screen is not designed as per figma

packages/modules/tl/src/pageComponents/TLOwnerDetailsEmployee.js
RAIN-3048 TL :: Able to create Trade license application with single owner's details when Ownership details category is selected as Multiple Owner
=> RAIN-3048 TL :: Able to create Trade license application with single owner's details when Ownership details category is selected as Multiple Owner

packages/modules/mCollect/src/pages/employee/Inbox.js
RAIN-3208 mCollect :: On clicking on rows per page dropdown, employee inbox blinks once and then opens.
=> RAIN-3208 mCollect :: On clicking on rows per page dropdown, employee inbox blinks once and then opens.

packages/modules/tl/src/pages/employee/index.js
RAIN-3202 TL :: Employee :: Breadcrumbs is not proper on these screens
=> RAIN-3202 TL :: Employee :: Breadcrumbs is not proper on these screens

packages/libraries/src/utils/index.js, packages/modules/tl/src/components/TLCard.js
RAIN-3162 added TL card access
=> RAIN-3162 added TL card access

packages/modules/tl/src/pageComponents/SelectOwnerShipDetails.js, packages/modules/tl/src/pageComponents/TLAccessoriesEmployee.js, packages/modules/tl/src/pageComponents/TLOwnerDetailsEmployee.js, packages/modules/tl/src/pageComponents/TLSelectAddress.js, packages/modules/tl/src/pageComponents/TLTradeDetailsEmployee.js, packages/modules/tl/src/pageComponents/TLTradeUnitsEmployee.js
RAIN-3280 TL :: Few fields are not disabled while re-submitting application from Counter employee and able to submit by editing those fields
=> RAIN-3280 TL :: Few fields are not disabled while re-submitting application from Counter employee and able to submit by editing those fields

packages/libraries/src/hooks/tl/useInbox.js, packages/modules/tl/src/components/inbox/DesktopInbox.js, packages/modules/tl/src/components/inbox/MobileInbox.js
=> RAIN-3285 : TL Inbox added field in table to show Application type

packages/modules/hrms/src/components/EmployeeAction.js, packages/modules/hrms/src/components/Modal/EmployeeActivation.js, packages/modules/hrms/src/components/Modal/EmployeeAppliaction.js, packages/modules/pt/src/components/inbox/Status.js, packages/modules/tl/src/components/inbox/InboxFilter.js
=> RAIN-3288 : HRMS Effective date field is set with todays date and disabled

packages/modules/tl/src/pageComponents/SelectOwnerShipDetails.js, packages/modules/tl/src/pageComponents/TLAccessoriesEmployee.js, packages/modules/tl/src/pageComponents/TLDocumentsEmployee.js, packages/modules/tl/src/pageComponents/TLOwnerDetailsEmployee.js, packages/modules/tl/src/pageComponents/TLSelectAddress.js, packages/modules/tl/src/pageComponents/TLTradeDetailsEmployee.js, packages/modules/tl/src/pageComponents/TLTradeUnitsEmployee.js
RAIN-3293 TL :: Employee Create :: Asterisk mark should be provided for mandatory fields in create flow
=> RAIN-3293 TL :: Employee Create :: Asterisk mark should be provided for mandatory fields in create flow

packages/modules/tl/src/components/SearchApplication.js, packages/modules/tl/src/components/SearchLicense.js
=> UAT Fix : TL: Search status locale prefix changed in search trade and  application screens

packages/modules/tl/src/pageComponents/TLAccessoriesEmployee.js, packages/modules/tl/src/pageComponents/TLOwnerDetailsEmployee.js, packages/modules/tl/src/pageComponents/TLTradeUnitsEmployee.js
RAIN-3091 updated icons, styles
=> RAIN-3091 updated icons, styles

packages/modules/templates/ApplicationDetails/Modal/index.js
RAIN-3091 fixed error for cancel renewal application
=> RAIN-3091 fixed error for cancel renewal application

packages/modules/core/src/components/TopBarSideBar/SideBar/CitizenSideBar.js, packages/modules/core/src/components/TopBarSideBar/SideBar/index.js, packages/modules/core/src/config/sidebar-menu.js
=> RAIN-3329 :  Common home button in side bar issue fixed to navigate to employee home screen

packages/modules/common/src/payments/employee/payment-collect/index.js, packages/modules/tl/src/pageComponents/SelectOwnerShipDetails.js, packages/react-components/src/atoms/Toast.js
RAIN-3336 TL :: Hard Code Values in TL Employee and mCollect review comments
=> RAIN-3336 TL :: Hard Code Values in TL Employee and mCollect review comments

packages/modules/tl/src/components/SearchLicense.js, packages/modules/tl/src/pageComponents/TLDocumentsEmployee.js, packages/modules/tl/src/pageComponents/TLTradeDetailsEmployee.js
RAIN-3356 TL :: Observation by PO
=> RAIN-3356 TL :: Observation by PO

packages/modules/hrms/src/Module.js, packages/modules/hrms/src/components/config/config.js, packages/modules/hrms/src/components/inbox/DesktopInbox.js, packages/modules/hrms/src/components/inbox/MobileInbox.js, packages/modules/hrms/src/components/pageComponents/Banner.js, packages/modules/hrms/src/pages/EmployeeDetails.js
=> RAIN-3355 : HRMS added remarks detail in Employee details and changed…few alignment in create

packages/modules/tl/src/components/SearchLicense.js, packages/modules/tl/src/components/TLCard.js, packages/modules/tl/src/pages/employee/ApplicationDetails.js, packages/modules/tl/src/pages/employee/index.js
RAIN-3356 Breadcrumb issues in TL fixed
=> RAIN-3356 Breadcrumb issues in TL fixed

packages/modules/tl/src/components/SearchApplication.js, packages/modules/tl/src/components/SearchLicense.js
RAIN-3367 TL :: Entered search parameters are not cleared after clicking on Clear Search and same params are used in the next Search API request
=> RAIN-3367 TL :: Entered search parameters are not cleared after clicking on Clear Search and same params are used in the next Search API request

packages/modules/fsm/src/pageComponents/SelectStreet.js, packages/modules/tl/src/pageComponents/TLAccessoriesEmployee.js, packages/modules/tl/src/pageComponents/TLSelectGeolocation.js, packages/modules/tl/src/pages/employee/ReNewApplication/index.js
=> RAIN-3382: Edit / Renew Tl enabled to edit  Accessory , Street and door no fields
